### ISSUE TITLE
Generating Docker Artifacts hang-up

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#593]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/develop/deploy-on-docker/

When the project is being built after adding the docker configs, it hangs up in Generating docker artifacts.
```
Generating docker artifacts...
	@docker 		 - complete 1/3 
```

**Suggested Labels:**
Priority/high
Severity/Blocker
type/bug

**Affected Product Version:**
EI 7.0

**Steps to reproduce:**
1. Follow the steps in https://ei.docs.wso2.com/en/latest/ballerina-integrator/develop/deploy-on-docker/
2. Build the module

**Expected**: Executable jar is generated and the docker image should be created. 
**Actual**: Docker image does not get created.

**Comment by hemikak** [comment]
It may be download the docker image from docker hub. How long did it hang for ?

**Comment by isuruuy429** [comment]
It took more than 20 minutes but never completed.

**Comment by isuruuy429** [comment]
I retired this and it went created within 1-2 minutes. Hence closing the bug.

**Comment by hemikak** [comment]
When using @docker annotation in ballerina it creates a docker image having the "openjdk:8-jre-alpine" base image. So if the "openjdk:8-jre-alpine" image is not there in the local registry, it will download it from docker hub. So that progress is not show in the command output. It feels as if hanged. Once that is pulled for the first time, the consequent builds will be fast as the base image is already there in the local registry. Its the first build that takes time.
